default_stages: ['pre-commit']
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  - repo: https://github.com/bwhmather/ssort
    rev: 0.14.0
    hooks:
      - id: ssort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.10
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff-check

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.6.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
